[project]
name = "jvp_flash_attention"
version = "0.13.0"
description = "Flash Attention Triton kernel with support for second-order derivatives"
authors = [
    { name = "Alex Morehead", email = "alex.morehead@gmail.edu" }
]
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = [
    'artificial intelligence',
    'deep learning',
]

classifiers=[
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.10',
]

dependencies = [
    # --------- pytorch --------- #
    "torch>=2.8.0",
    "torchvision>=0.23",

    # --------- others --------- #
    # "numpy>=2.2.6",
]

[project.urls]
Homepage = "https://pypi.org/project/jvp_flash_attention/"
Repository = "https://github.com/amorehead/jvp-flash-attention"

[project.optional-dependencies]
lint = ["pre-commit>=4.3.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
pythonpath = [
  "."
]
addopts = [
  "--color=yes",
  "--durations=0",
  "--strict-markers",
  "--doctest-modules",
]
filterwarnings = [
  "ignore::DeprecationWarning",
  "ignore::UserWarning",
]
log_cli = "True"
markers = [
  "slow: slow tests",
]
minversion = "6.0"
testpaths = "tests/"

# Assuming you're developing for Python 3.10
target-version = "py310"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["jvp_flash_attention"]

[tool.coverage.report]
exclude_lines = [
    "pragma: nocover",
    "raise NotImplementedError",
    "raise NotImplementedError()",
    "if __name__ == .__main__.:",
]
